import 'dart:convert';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../config/constants.dart';
import '../models/user.dart';
import '../models/job.dart';
import '../models/program.dart';
import '../models/certificate.dart';

class StorageService {
  static late Box _userBox;
  static late Box _jobsBox;
  static late Box _programsBox;
  static late Box _settingsBox;
  static late Box _cacheBox;
  static late SharedPreferences _prefs;
  static const _secureStorage = FlutterSecureStorage(
    aOptions: AndroidOptions(encryptedSharedPreferences: true),
    iOptions: IOSOptions(accessibility: KeychainAccessibility.first_unlock),
  );

  // Initialize storage
  static Future<void> init() async {
    // Register Hive adapters
    _registerAdapters();
    
    // Open Hive boxes
    _userBox = await Hive.openBox(AppConstants.userBox);
    _jobsBox = await Hive.openBox(AppConstants.jobsBox);
    _programsBox = await Hive.openBox(AppConstants.programsBox);
    _settingsBox = await Hive.openBox(AppConstants.settingsBox);
    _cacheBox = await Hive.openBox(AppConstants.cacheBox);
    
    // Initialize SharedPreferences
    _prefs = await SharedPreferences.getInstance();
  }

  static void _registerAdapters() {
    // Register all Hive type adapters here
    // These will be generated by hive_generator
    // Hive.registerAdapter(UserAdapter());
    // Hive.registerAdapter(WorkExperienceAdapter());
    // Hive.registerAdapter(EducationAdapter());
    // Hive.registerAdapter(JobAdapter());
    // Hive.registerAdapter(CompanyAdapter());
    // Hive.registerAdapter(JobApplicationAdapter());
    // Hive.registerAdapter(ProgramAdapter());
    // Hive.registerAdapter(ProgramModuleAdapter());
    // Hive.registerAdapter(ModuleLessonAdapter());
    // Hive.registerAdapter(ProgramEnrollmentAdapter());
    // Hive.registerAdapter(CertificateAdapter());
  }

  // ============ Secure Storage (Tokens) ============

  static Future<void> saveTokens(String accessToken, String refreshToken) async {
    await _secureStorage.write(key: AppConstants.accessTokenKey, value: accessToken);
    await _secureStorage.write(key: AppConstants.refreshTokenKey, value: refreshToken);
  }

  static Future<String?> getAccessToken() async {
    return await _secureStorage.read(key: AppConstants.accessTokenKey);
  }

  static Future<String?> getRefreshToken() async {
    return await _secureStorage.read(key: AppConstants.refreshTokenKey);
  }

  static Future<void> clearTokens() async {
    await _secureStorage.delete(key: AppConstants.accessTokenKey);
    await _secureStorage.delete(key: AppConstants.refreshTokenKey);
  }

  // ============ User Data ============

  static Future<void> saveUser(User user) async {
    await _userBox.put(AppConstants.userDataKey, user.toJson());
  }

  static User? getUser() {
    final data = _userBox.get(AppConstants.userDataKey);
    if (data == null) return null;
    return User.fromJson(Map<String, dynamic>.from(data));
  }

  static Future<void> clearUser() async {
    await _userBox.delete(AppConstants.userDataKey);
  }

  // ============ Jobs Cache ============

  static Future<void> cacheJobs(List<Job> jobs, {String? key}) async {
    final cacheKey = key ?? 'all_jobs';
    final jobsJson = jobs.map((j) => j.toJson()).toList();
    await _jobsBox.put(cacheKey, {
      'data': jobsJson,
      'timestamp': DateTime.now().toIso8601String(),
    });
  }

  static List<Job>? getCachedJobs({String? key}) {
    final cacheKey = key ?? 'all_jobs';
    final cached = _jobsBox.get(cacheKey);
    if (cached == null) return null;

    final timestamp = DateTime.parse(cached['timestamp']);
    if (DateTime.now().difference(timestamp) > AppConstants.jobsCacheDuration) {
      return null; // Cache expired
    }

    final List<dynamic> data = cached['data'];
    return data.map((j) => Job.fromJson(Map<String, dynamic>.from(j))).toList();
  }

  static Future<void> saveJob(Job job) async {
    final savedJobs = getSavedJobs();
    if (!savedJobs.any((j) => j.id == job.id)) {
      savedJobs.add(job);
      final jobsJson = savedJobs.map((j) => j.toJson()).toList();
      await _jobsBox.put(AppConstants.savedJobsKey, jobsJson);
    }
  }

  static Future<void> removeSavedJob(String jobId) async {
    final savedJobs = getSavedJobs();
    savedJobs.removeWhere((j) => j.id == jobId);
    final jobsJson = savedJobs.map((j) => j.toJson()).toList();
    await _jobsBox.put(AppConstants.savedJobsKey, jobsJson);
  }

  static List<Job> getSavedJobs() {
    final data = _jobsBox.get(AppConstants.savedJobsKey);
    if (data == null) return [];
    final List<dynamic> jobsData = data;
    return jobsData.map((j) => Job.fromJson(Map<String, dynamic>.from(j))).toList();
  }

  static bool isJobSaved(String jobId) {
    return getSavedJobs().any((j) => j.id == jobId);
  }

  // ============ Programs Cache ============

  static Future<void> cachePrograms(List<Program> programs, {String? key}) async {
    final cacheKey = key ?? 'all_programs';
    final programsJson = programs.map((p) => p.toJson()).toList();
    await _programsBox.put(cacheKey, {
      'data': programsJson,
      'timestamp': DateTime.now().toIso8601String(),
    });
  }

  static List<Program>? getCachedPrograms({String? key}) {
    final cacheKey = key ?? 'all_programs';
    final cached = _programsBox.get(cacheKey);
    if (cached == null) return null;

    final timestamp = DateTime.parse(cached['timestamp']);
    if (DateTime.now().difference(timestamp) > AppConstants.programsCacheDuration) {
      return null; // Cache expired
    }

    final List<dynamic> data = cached['data'];
    return data.map((p) => Program.fromJson(Map<String, dynamic>.from(p))).toList();
  }

  // ============ Settings ============

  static Future<void> setOnboardingComplete(bool complete) async {
    await _prefs.setBool(AppConstants.onboardingCompleteKey, complete);
  }

  static bool isOnboardingComplete() {
    return _prefs.getBool(AppConstants.onboardingCompleteKey) ?? false;
  }

  static Future<void> setNotificationsEnabled(bool enabled) async {
    await _settingsBox.put(AppConstants.notificationsEnabledKey, enabled);
  }

  static bool areNotificationsEnabled() {
    return _settingsBox.get(AppConstants.notificationsEnabledKey, defaultValue: true);
  }

  static Future<void> setLocationEnabled(bool enabled) async {
    await _settingsBox.put(AppConstants.locationEnabledKey, enabled);
  }

  static bool isLocationEnabled() {
    return _settingsBox.get(AppConstants.locationEnabledKey, defaultValue: false);
  }

  // ============ Recent Searches ============

  static Future<void> addRecentSearch(String query) async {
    final searches = getRecentSearches();
    searches.remove(query); // Remove if exists
    searches.insert(0, query); // Add to beginning
    if (searches.length > 10) {
      searches.removeLast(); // Keep only 10 recent searches
    }
    await _cacheBox.put(AppConstants.recentSearchesKey, searches);
  }

  static List<String> getRecentSearches() {
    final data = _cacheBox.get(AppConstants.recentSearchesKey);
    if (data == null) return [];
    return List<String>.from(data);
  }

  static Future<void> clearRecentSearches() async {
    await _cacheBox.delete(AppConstants.recentSearchesKey);
  }

  // ============ Generic Cache ============

  static Future<void> cacheData(String key, dynamic data, {Duration? expiry}) async {
    await _cacheBox.put(key, {
      'data': data,
      'timestamp': DateTime.now().toIso8601String(),
      'expiry': expiry?.inSeconds,
    });
  }

  static T? getCachedData<T>(String key) {
    final cached = _cacheBox.get(key);
    if (cached == null) return null;

    final timestamp = DateTime.parse(cached['timestamp']);
    final expirySeconds = cached['expiry'];
    
    if (expirySeconds != null) {
      final expiry = Duration(seconds: expirySeconds);
      if (DateTime.now().difference(timestamp) > expiry) {
        return null; // Cache expired
      }
    }

    return cached['data'] as T;
  }

  static Future<void> removeCachedData(String key) async {
    await _cacheBox.delete(key);
  }

  // ============ Clear All ============

  static Future<void> clearAll() async {
    await clearTokens();
    await _userBox.clear();
    await _jobsBox.clear();
    await _programsBox.clear();
    await _settingsBox.clear();
    await _cacheBox.clear();
    await _prefs.clear();
  }

  static Future<void> clearCache() async {
    await _cacheBox.clear();
  }
}
